model:
  task: lp  # which tasks to train on, can be any of [lp, nc]
  model: HNN  # which encoder to use, can be any of [Shallow, MLP, HNN, GCN, GAT, HyperGCN]
  dim: 16  # embedding dimension
  manifold: PoincareBall  # which manifold to use, can be any of [Euclidean, Hyperboloid, PoincareBall]
  dropout: 0.2  # dropout probability
  drop_mode: weight  # feature,weight
  c: 1.0  # hyperbolic radius, set to None for trainable curvature
  r: 2.0  # fermi-dirac decoder parameter for lp
  t: 1.0  # fermi-dirac decoder parameter for lp
  pos_weight: 0  # whether to upweight positive class in node classification tasks
  num_layers: 2  # number of hidden layers in encoder
  bias: 1  # whether to use bias (1) or not (0)
  act: null  # relu, null

transformation:
  transform_mode: HFC # Table 4: Mobius, Einstein, LorentzTan, LFC, NestFC, PoincareFC, HFC
  gyrobias: true # append gyroaddition bias after PoincareFC and LFC
  normalize_v: false # normalize [v_1, ..., v_i, ...] before Exp_0; important for HFC-H reproduction, where this must be true

##### Other param for HGCN
#  pretrained_embeddings: null  # path to pretrained embeddings (.npy file) for Shallow node classification
#  use-att: 0  # whether to use hyperbolic attention or not
#  local-agg: 0  # whether to local tangent space aggregation or not
#  n-heads: 4  # number of attention heads for graph attention networks, must be a divisor dim
#  alpha: 0.2  # alpha for leakyrelu in graph attention networks

optimizer:
  lr: 0.01  # learning rate
  weight_decay: 0.001  # l2 regularization strength
  optimizer: Adam
  momentum: 0.999  # momentum in optimizer
  gamma: 0.5  # gamma for lr scheduler
  amsgrad: False
